stages:
- sonarqube_analysis
- next_version
- project_build
- deploy_to_aws
- semantic_release

.rules-standard: &rules-standard
  - if: $CI_COMMIT_BRANCH !~ /^(main|develop)$/ && $CI_PIPELINE_SOURCE =~ /^push|merge_request_event$/
    when: never
  - when: on_success

.rules-mr: &rules-mr
- if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "develop" && $CI_PIPELINE_SOURCE == "merge_request_event"
- if: $CI_PIPELINE_SOURCE == "schedule" && $RUN_ANALYTICS == "true"
  variables:
    SONAR_QG_WAIT: "false"
  when: always

.verify_publish: &verify_publish
  - echo $CAN_PUBLISH
  - >
    if [ $CAN_PUBLISH == "false" ]; then
      echo "Ignorando Job  $CI_JOB_NAME por a ENV CAN_PUBLISH estar com valor 'false'";
      exit 0;
    fi;

sonarqube_analysis:
  stage: sonarqube_analysis
  image: algaworks/devops-sonar-scanner-cli:v1.0.0
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
    GIT_DEPTH: "0"
  script: 
    - |
       sonar-scanner -Dsonar.projectKey=${SONAR_PROJECT_KEY} \
       -Dsonar.sources=. \
       -Dsonar.host.url=${SONAR_HOST_URL} \
       -Dsonar.login=${SONAR_TOKEN} \
       -Dsonar.qualitygate.wait=${SONAR_QG_WAIT}
    - |
      sleep 10s
      SONAR_RESULT=$(curl -u "${SONAR_TOKEN}:" "${SONAR_HOST_URL}/api/qualitygates/project_status?projectKey=${SONAR_PROJECT_KEY}")
      METRICS_RESULT=$(curl -u "${SONAR_TOKEN}:" "${SONAR_HOST_URL}/api/measures/component?component=${SONAR_PROJECT_KEY}&metricKeys=new_bugs,new_vulnerabilities,new_code_smells,new_security_hotspots,new_coverage,new_duplicated_lines_density")
     
      if echo "$SONAR_RESULT" | jq -e 'has("errors")' > /dev/null; then
        echo "Error fetching quality gate: $(echo $SONAR_RESULT | jq -r '.errors[].msg')"
      else
         QUALITY_GATE_STATUS=$(echo $SONAR_RESULT | jq -r '.projectStatus.status // "UNKNOWN"')
      fi

      if echo "$METRICS_RESULT" | jq -e 'has("errors")' > /dev/null; then
        echo "Error fetching metrics: $(echo $METRICS_RESULT | jq -r '.errors[].msg')"
      else 
        BUGS=$(echo $METRICS_RESULT | jq -r '.component.measures[] | select(.metric=="new_bugs") | .period.value')
        CODE_SMELLS=$(echo $METRICS_RESULT | jq -r '.component.measures[] | select(.metric=="new_code_smells") | .period.value')
        VULNERABILITIES=$(echo $METRICS_RESULT | jq -r '.component.measures[] | select(.metric=="new_vulnerabilities") | .period.value')
        HOTSPOTS=$(echo $METRICS_RESULT | jq -r '.component.measures[] | select(.metric=="new_security_hotspots") | .period.value')
        DUPLICATIONS=$(echo $METRICS_RESULT | jq -r '.component.measures[] | select(.metric=="new_duplicated_lines_density") | .period.value')
        COVERAGE=$(echo $METRICS_RESULT | jq -r '.component.measures[] | select(.metric=="new_coverage") | .period.value')
        
        METRICS_MR_RESULT="#### Metrics
        - 🐛 Issues: ${BUGS:-0} bugs, ${VULNERABILITIES:-0} vulnerabilities, ${CODE_SMELLS:-0} code smells
        - 🎯 Security Hotspots Coverage: ${HOTSPOTS:-0}
        - 🔄 Code Duplication: ${DUPLICATIONS:-0.0}%
        - 📊 Coverage: ${COVERAGE:-0.0}%
        
         [View Detailed Results](${SONAR_HOST_URL}/dashboard?id=${SONAR_PROJECT_KEY})"
      fi

      
      echo "Quality Gate Status: $QUALITY_GATE_STATUS"
      if [ "$QUALITY_GATE_STATUS" = "ERROR" ]; then
        STATUS_EMOJI=$(echo "❌")
        EXIT_STATUS=$(echo "1")
      elif [ "$QUALITY_GATE_STATUS" = "OK" ]; then
        STATUS_EMOJI=$(echo "✅")
        EXIT_STATUS=$(echo "0")
      else
        EXIT_STATUS=$(echo "1") 
        STATUS_EMOJI=$(echo "☢️")
        QUALITY_GATE_STATUS=$(echo "Falha ao Obter Status da Quality Gate")
        echo $QUALITY_GATE_STATUS
      fi
    
      MERGE_REQUEST_IID=$(echo $CI_MERGE_REQUEST_IID)
      if [ ! -z "$MERGE_REQUEST_IID" ]; then
        COMMENT="### SonarQube Analysis Results

        **Quality Gate Status:** ${STATUS_EMOJI} ${QUALITY_GATE_STATUS}

        ${METRICS_MR_RESULT}
        ---
        *This comment was automatically generated by the CI/CD pipeline.*"      
        
        curl --request POST \
          --header "PRIVATE-TOKEN: ${GITLAB_TOKEN}" \
          --data-urlencode "body=${COMMENT}" \
          "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/merge_requests/${MERGE_REQUEST_IID}/notes"

        exit $EXIT_STATUS
      fi
  rules: *rules-mr

next_version:
  stage: next_version
  image: algaworks/devops-semantic-release:v1.0.0
  interruptible: false
  script:
  - echo "Definindo Build Type"
  - >
    if [[ "$CI_COMMIT_BRANCH" == "main" ]]; then
        BUILD_TYPE="prod"
    else
        BUILD_TYPE="dev"
    fi;
  - echo "Resolvendo Proxima Versão"
  - >
    npx semantic-release --dry-run --no-cli; if [[ ! -e .VERSION ]]; then
      CAN_PUBLISH="false"
      echo "$CI_COMMIT_BRANCH" > .VERSION
    elif [[ "$CI_COMMIT_BRANCH" == "main" ]]; then
      CAN_PUBLISH="true"
    fi;

  - echo "Declarando variáveis de ambiente"
  - echo "HELM_BRANCH=$CI_COMMIT_BRANCH" >> build.env
  - echo "NEXT_VERSION=$(cat .VERSION)" >> build.env
  - echo "CAN_PUBLISH=$CAN_PUBLISH" >> build.env
  - echo "BUILD_TYPE=$BUILD_TYPE" >> build.env
  artifacts:
    reports:
      dotenv: build.env
  rules: *rules-standard

project_build:
  stage: project_build
  image: node:20-alpine
  before_script:
  - npm install -g @angular/cli
  - ng version
  - npm install
  - >
    if [[ "$BUILD_TYPE" == "prod" ]]; then
       ENV_PATH=src/environments/environment.prod.ts
       sed -i "s|PRD_API_URL|$PRD_API_URL|g" $ENV_PATH
       sed -i "s|PRD_AUTH_URL|$PRD_AUTH_URL|g" $ENV_PATH
    fi;
  script:
  - npm run build:$BUILD_TYPE
  artifacts:
    paths:
    - $PROJECT_DIST_PATH
  rules: *rules-standard

deploy_to_aws:
  stage: deploy_to_aws
  image:
    name: amazon/aws-cli:2.21.2
    entrypoint: [ '/usr/bin/env' ]
  before_script:
  - *verify_publish
  - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
  - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
  script:
  - echo 'Deploying to S3 version -> $NEXT_VERSION'
  - aws s3 sync $PROJECT_DIST_PATH s3://$AWS_S3_BUCKET
  - echo 'Invalidating CloudFront distribution'
  - aws cloudfront create-invalidation --distribution-id $AWS_CLOUDFRONT_DISTRIBUTION_ID --paths "/*"
  rules:
  - if: $CI_COMMIT_BRANCH == "main" && $CI_PIPELINE_SOURCE == "push"
    when: always

semantic_release:
  stage: semantic_release
  image: algaworks/devops-semantic-release:v1.0.0
  interruptible: false
  script:
  - npx semantic-release
  rules: *rules-standard
  retry: 2
